
/**
*	Source : Parser.h
*	Description: Parser holds all the tokens generated by the scanner and parses the program using the grammer passed to it.
*				 It provides the interface to the grammer to access the next token, update the count of variables, function,
*				 and statments.
*/
#ifndef _PARSER_H
#define _PARSER_H

#include <vector>
#include "Token.h"
#include "Grammar.h"
#include "SymbolTable.h"

class Grammar;

class Parser
{
public:
	/*Consumes current token and moves to next token*/
	Token* nextToken();

	/*Retrives current token*/
	Token* curToken();
	
	/*Inserts a new token to the parser token list*/
	void addToken(Token *newToken);

	/*Starts parsing the program*/
	bool parseProgram();

	/*Returns SymbolTable reference*/
	SymbolTable* getSymbolTable();
	
	/*Initializes parsers and assigns grammer*/
	Parser(Grammar* newGrammar, SymbolTable* mySymTab);

	~Parser();

private:
	std::vector<Token *> *tokenVector;
	std::vector<Token *>::iterator tokenIT;

	Grammar* myGrammar;
	SymbolTable* mySymTab;
};
#endif
